### ISSUE TITLE
Needs to be added to CPAN

### ISSUE THREAD

**Issue by drzowie** [drzowie/PDL-Transform-Color#2]
PDL::Transform::Color needs to be uploaded to PAUSE, to enable some other modules (PDL::Graphics::Gnuplot).

**Comment by mohawk2** [comment]
It's already there, but apparently on BackPAN (i.e. it was there and got deleted). Since you have first-come and I don't recall releasing it then deleting it, I'm inferring someone (you? only the releaser of a distribution, or an admin, can do so) deleted it off PAUSE.

Karl did something very similar with ExtUtils::F77 a little while ago, and deleted the latest release off what he was calling the staging server. In fact, PAUSE is not a staging server but where everything gets mirrored from. If you delete a release off that, it stops being available entirely (except via BackPAN). Don't do that unless you mean it :-)

**Comment by drzowie** [comment]
Cool.  So, er, should I PAUSE it again?  Or will you?

Cheers,
Craig

**Comment by mohawk2** [comment]
I will - fixed a couple problems, still a bit more TLC needed ;-)

**Comment by mohawk2** [comment]
Released new version as 1.004

**Comment by drzowie** [comment]
Thank you so much, Ed!
